// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj_9M4U78RZSFG5AI5ppFbbwQCvODxcDY',
    appId: '1:1080944519562:web:b8cae3feee3017198f8073',
    messagingSenderId: '1080944519562',
    projectId: 'wordio-3b159',
    authDomain: 'wordio-3b159.firebaseapp.com',
    storageBucket: 'wordio-3b159.firebasestorage.app',
    measurementId: 'G-BMQD9XKT4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwKsFhRpyWlafdo78d_ux4lxzeqOhPiAc',
    appId: '1:1080944519562:android:6e8ec2e07396a3518f8073',
    messagingSenderId: '1080944519562',
    projectId: 'wordio-3b159',
    storageBucket: 'wordio-3b159.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQY-tj5b1P-06YDM-h846vkcWQstyeAw4',
    appId: '1:1080944519562:ios:ce14ff2632f81aaf8f8073',
    messagingSenderId: '1080944519562',
    projectId: 'wordio-3b159',
    storageBucket: 'wordio-3b159.firebasestorage.app',
    iosBundleId: 'com.example.wordio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQY-tj5b1P-06YDM-h846vkcWQstyeAw4',
    appId: '1:1080944519562:ios:ce14ff2632f81aaf8f8073',
    messagingSenderId: '1080944519562',
    projectId: 'wordio-3b159',
    storageBucket: 'wordio-3b159.firebasestorage.app',
    iosBundleId: 'com.example.wordio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj_9M4U78RZSFG5AI5ppFbbwQCvODxcDY',
    appId: '1:1080944519562:web:d8e046dbe1b3ee1d8f8073',
    messagingSenderId: '1080944519562',
    projectId: 'wordio-3b159',
    authDomain: 'wordio-3b159.firebaseapp.com',
    storageBucket: 'wordio-3b159.firebasestorage.app',
    measurementId: 'G-J09L2S30JK',
  );
}
